### ISSUE TITLE
Multi-frames gif lost pixels since the second frames.

### ISSUE THREAD

**Issue by ausk** [bunkahle/gif2numpy#1]
Thank you for your nice work. I test the `numpy` for multi-frames gif using [the earth gif](https://github.com/bunkahle/gif2numpy/blob/master/Images/Rotating_earth.gif), but I meet an issue. The frames lost pixels since the second. The size change from `(330, 330)` to `(232, 232)` and the pixels' values also become strange. 

![image](https://user-images.githubusercontent.com/4545060/56478469-340a7d80-64e2-11e9-859b-6f105a2def88.png)

You can try to reproduce in the following code.  

```
# 2019/04/22 
import cv2
import numpy as np
import gif2numpy as gif

fpath = "rotating_earth.gif"
frames, exts, image_specs = gif.convert(fpath)
print(len(frames))

while True:
    cv2.imshow("gif", frames[i])
    print(i, frames[i].shape)
    if cv2.waitKey(100)&0xFF == 27:
        break
    i = (i+1)%nums

cv2.destroyAllWindows()
```

**Comment by bunkahle** [comment]
Hi ausk,

the code has been bugfixed in version 1.2 and it should display all the frames properly.
